[package]
name = "vrm_layer_mate"
version = "0.1.0"
edition = "2024"

[dependencies]
gltf = "1.4.1"
gtk = { version = "0.9.7", package = "gtk4", features = ["v4_18"] }
gtk4-layer-shell = "0.5.0"
gtk4_glium = { git = "https://github.com/BB223/gtk4-glium", version = "0.4.0" }
