[package]
name = "vrm_layer_mate"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = "0.18.0"
epoxy = "0.1.0"
glium = "0.36.0"
gltf = "1.4.1"
gtk = { version = "0.9.7", package = "gtk4", features = ["v4_18"] }
gtk4-layer-shell = "0.5.0"
libloading = "0.8.8"
